spring:
  datasource:
    url: jdbc:mysql://localhost/trazar?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: 

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:  
      ddl-auto: update
      
server:
  error:
    include-message: always